*DECK XERMSG
        SUBROUTINE XERMSG (LIBRAR, SUBROU, MESSG, NERR, LEVEL)
        CHARACTER*(*) LIBRAR, SUBROU, MESSG
        INTEGER NERR, LEVEL
        EXTERNAL RFXSL0
        CALL RFXSL0(LIBRAR, SUBROU, MESSG, NERR, LEVEL)
        RETURN
        END